"""Initial schema

Revision ID: 421f5e59c8d5
Revises: 859ff58e7453
Create Date: 2025-12-30 15:42:04.868575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421f5e59c8d5'
down_revision = '859ff58e7453'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magic_login_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_magic_tokens_valid', 'magic_login_tokens', ['email', 'expires_at'], unique=False)
    op.create_index(op.f('ix_magic_login_tokens_email'), 'magic_login_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_magic_login_tokens_expires_at'), 'magic_login_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_magic_login_tokens_token_hash'), 'magic_login_tokens', ['token_hash'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_active', 'sessions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_index('idx_sessions_active', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_magic_login_tokens_token_hash'), table_name='magic_login_tokens')
    op.drop_index(op.f('ix_magic_login_tokens_expires_at'), table_name='magic_login_tokens')
    op.drop_index(op.f('ix_magic_login_tokens_email'), table_name='magic_login_tokens')
    op.drop_index('idx_magic_tokens_valid', table_name='magic_login_tokens')
    op.drop_table('magic_login_tokens')
    # ### end Alembic commands ###
